azureTenant: trygdeetaten.no
environment: dev
replicas_min: 1
replicas_max: 2
cpu: 400m
memory: 768Mi
external-host:
  - pdl-api.dev-fss-pub.nais.io
env:
  SPRING_PROFILES_ACTIVE: default
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api