azureTenant: trygdeetaten.no
environment: dev
replicas_min: 1
replicas_max: 2
cpu: 50m
memory: 512Mi
external-host:
  - testnav-brregstub-reverse-proxy.dev-fss-pub.nais.io
env:
  SPRING_PROFILES_ACTIVE: default, dev
  BRREG_STUB_API_URL: https://testnav-brregstub-reverse-proxy.dev-fss-pub.nais.io
  BRREG_STUB_AAD_CLIENT_ID: dev-fss.dolly.testnav-brregstub-reverse-proxy
