azureTenant: trygdeetaten.no
environment: dev
replicas_min: 1
replicas_max: 2
cpu: 400m
memory: 768Mi
env:
  SPRING_PROFILES_ACTIVE: default, dev
  BRREG_STUB_API_URL: https://brreg-stub.intern.dev.nav.no