---
apiVersion: "nais.io/v1"
kind: "AzureAdApplication"
metadata:
  name: flex-brreg-proxy-nav-tenant-proxy
  namespace: flex
  labels:
    team: flex
spec:
  secretName: azure-flex-brreg-proxy-nav-tenant-proxy
  secretKeyPrefix: NAV_TENANT_PROXY
  tenant: nav.no
---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-brreg-proxy
  namespace: flex
  labels:
    team: flex
  annotations:  
    config.linkerd.io/proxy-outbound-connect-timeout: 10s
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: {{azureTenant}}
  accessPolicy:
    outbound:
      external:
    {{#each external-host}}
        - host: {{this}}
    {{/each}}
    inbound:
      rules:
        - application: sykepengesoknad-backend
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  envFrom:
    - secret: brreg-auth
    - secret: azure-flex-brreg-proxy-nav-tenant-proxy
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
