azureTenant: nav.no
environment: prod
replicas_min: 2
replicas_max: 3
cpu: 50m
memory: 640Mi
external-host:
  - grunndata.brreg.no
env:
  SPRING_PROFILES_ACTIVE: default, prod
  BRREG_URL: https://grunndata.brreg.no/grunndata/ErFr
