server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: health,prometheus

logging.config: "classpath:logback.xml"
nais.cluster: ${NAIS_CLUSTER_NAME}


no.nav.security.jwt:
  issuer:
    azureator:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      brreg-stub-proxy-client-credentials:
        # Bruker variabler fra flex-brreg-proxy-nav-tenant-proxy
        token-endpoint-url: ${AZURE_NAV_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${BRREG_STUB_AAD_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_NAV_APP_CLIENT_ID}
          client-secret: ${AZURE_NAV_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic